### ISSUE TITLE
Missing Date column in Notion template DB

### ISSUE THREAD

**Issue by aliyome** [azu/bluenotiondb#14]
I found that the [Notion Template DB linked from the README](https://efcl.notion.site/Demo-Bluenotion-0f9885a393874c2aa7a4765ff5ddf0be
) is missing a Date column.
When I run the `bluenotiondb` command, it results in an error stating that the Date column is missing.
After I manually added the Date column to the database, the `bluenotiondb` command executed successfully.

Can you add a Date column to the template DB?

## Steps to Reproduce

- Follow the README to set up the Notion Template DB.
- Run bluenotiondb command.

## Error log

```fish
~/r/bluenotiondb (main|✔) [1] $ bun run main
$ CACHE_DIR=$(pwd)/.cache DEBUG=1 bun run src/index.ts
@notionhq/client warn: request fail {
  code: "validation_error",
  message: "Could not find sort property with name or id: Date"
}
1 | (function (...args) { super(...args); })
                                   ^
APIResponseError: Could not find sort property with name or id: Date
 code: "validation_error"

      at new NotionClientErrorBase (:1:32)
      at new HTTPResponseError (/Users/aliyome/repos/bluenotiondb/node_modules/@notionhq/client/build/src/errors.js:81:8)
      at new APIResponseError (/Users/aliyome/repos/bluenotiondb/node_modules/@notionhq/client/build/src/errors.js:151:8)
      at buildRequestError (/Users/aliyome/repos/bluenotiondb/node_modules/@notionhq/client/build/src/errors.js:162:15)
      at /Users/aliyome/repos/bluenotiondb/node_modules/@notionhq/client/build/src/Client.js:347:16
error: script "main" exited with code 1 (SIGHUP)
```

**Comment by azu** [comment]
Ah, Thanks for report!

**Comment by azu** [comment]
https://www.notion.so/efcl/Demo-Bluenotion-0f9885a393874c2aa7a4765ff5ddf0be?pvs=4
Added
